### ISSUE TITLE
create `index.html`

### ISSUE THREAD

**Issue by yarigpopov** [new-hope/AngularJS#1]
Please, create `index.html` in the root of the project with links to all tasks and check will the `gh-pages` work (show content of this `index.html`)

**Comment by Grishchenko** [comment]
Слав, привет. Сделал, если я правильно понял задание.

**Comment by yarigpopov** [comment]
в целом, именно то, что надо. теперь все можно открыть по ссылке
https://new-hope.github.io/AngularJS/

одно маленькое замечание:
https://github.com/new-hope/AngularJS/blob/master/index.html#L34
чекбокс как управляющий элемент открытия списка довольно необычно. 
я бы заменил 
``` 
<th><input type="checkbox" ng-model="selected[$index]"></th>
```
на

**Comment by Grishchenko** [comment]
Слав, на что бы ты заменил?

**Comment by yarigpopov** [comment]
я бы хотел увидеть там ссылку, с надписью "Show" или "Hide" в зависимости от статуса

если не сможешь, вот мой вариант)
https://gist.github.com/chilicoder/53943098c50c6958182c28856bf69e87#file-answer-html

**Comment by Grishchenko** [comment]
Я думал над похожим вариантом, но решил сделать через чекбокс. Это мне кажется вопрос презентабельности. Суть от этого не меняется.

**Comment by yarigpopov** [comment]
Меняется. Интерфейс перестает быть понятным.

**Comment by yarigpopov** [comment]
@Grishchenko ты забыл новый раздел в index.html добавить
